[package]
authors = ["Félix Saparelli <felix@passcod.name>"]
description = "“Why did I block/mute/follow/unfollow X?!”"
edition = "2018"
name = "reasonable"
publish = false
version = "0.1.0"

[dependencies]
sodiumoxide = "0.2.0"
